export const inTextShortCuts: Record<string, string> = {
  BOZP: "bezpečnost a ochrana zdraví při práci",
  CP: "Centrální podatelna",
  ČR: "Česká republika",
  EO: "Ekonomický odbor",
  EP: "Evropský parlament",
  EU: "Evropská unie",
  "FN Brno": "Fakultní nemocnice Brno",
  GDPR: "ochrana osobních údajů",
  IŘD: "interní řídicí dokumentace",
  IT: "informační technologie",
  KŘ: "Kancelář ředitele",
  LN: "Lotus Notes",
  LPP: "léčebná a preventivní péče",
  "MZ ČR": "Ministerstvo zdravotnictví České republiky",
  NLZP: "nelékařský zdravotnický pracovník",
  NP: "nadzemní podlaží",
  NS: "nákladové středisko",
  OP: "Oddělení pověřence",
  OSS: "Oddělení spisové služby",
  PO: "požární ochrana",
  ŘDF: "řízená dokumentace firmy",
  SŘK: "systém řízení kvality",
  SÚJB: "Státní ústav pro jadernou bezpečnost",
  SÚKL: "Státní ústav pro kontrolu léčiv",
  ÚOOÚ: "Úřad pro ochranu osobních údajů",
  ÚSV: "úplné středoškolské vzdělání",
  VŠV: "vysokoškolské vzdělání",
  "WISPI-SSL": "elektronický systém pro evidenci pošty",
};
